### ISSUE TITLE
Stress accents on the top of the long/short markers

### ISSUE THREAD

**Issue by niru86** [tweh/metrix#16]
It would be great to have the possibilty to put stress accents on the top of the long/short markers just like the package [metre](https://ctan.org/pkg/metre) did, e.g. in this example here:

![screenshot-2017-10-16 demo pdf](https://user-images.githubusercontent.com/16512311/31625772-94d97696-b2a7-11e7-95c3-7be4f3fec63b.png)

**Comment by tweh** [comment]
Hi,

thanks for the suggestion. I think this could be possible. Unfortunately at the moment I’m quite busy but I’ll take a look at it if I finde some time …

**Comment by tweh** [comment]
This is now possible by adding a grave or acute bevor the symbol (at the moment only for breve and longum).

**Comment by tweh** [comment]
Syntax change: use `/` (slash) for an acute or `*` (asterisk) for a grave accent.
